/********************************************************************
**       This head file is generated by program,                   **
**            Please do not change it directly.                    **
**                   Auther: brinkqiang                            **
********************************************************************/
// source: pymsgpack.pkg

#ifndef __PYMSGPACK_PYBIND11_H__
#define __PYMSGPACK_PYBIND11_H__

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
}
#endif

#endif  // __PYMSGPACK_PYBIND11_H__
