/********************************************************************
**       This cc file is generated by program,                     **
**            Please do not change it directly.                    **
**                   Auther: brinkqiang                            **
********************************************************************/
// source: pymsgpack.pkg

#include "pymsgpack.pybind11.h"


#include "msgpack_loader.hpp"


#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <algorithm>

PYBIND11_MODULE(pymsgpack, m) {

    pybind11::class_<creature_attr_def>(m, "creature_attr_def")
    .def(pybind11::init<>())
    .def_readwrite("maximun", &creature_attr_def::maximun)
    .def_readwrite("minimun", &creature_attr_def::minimun)
    .def_readwrite("use_centimeter", &creature_attr_def::use_centimeter)
    .def_readwrite("key", &creature_attr_def::key)
    .def_readwrite("defs", &creature_attr_def::defs)
    .def_readwrite("type", &creature_attr_def::type)
    .def_readwrite("desc", &creature_attr_def::desc)
    .def_readwrite("desc_bit", &creature_attr_def::desc_bit);

    pybind11::class_<creature_attr_def_data>(m, "creature_attr_def_data")
    .def(pybind11::init<>())
    .def("add", &creature_attr_def_data::add)
    .def("get", &creature_attr_def_data::get)
    .def("to_msgpack", &creature_attr_def_data::to_msgpack)
    .def("from_msgpack", &creature_attr_def_data::from_msgpack)
    .def_readwrite("datas", &creature_attr_def_data::datas);

    pybind11::class_<CMsgPackLoader>(m, "CMsgPackLoader")
    .def(pybind11::init<>())
    .def("load", &CMsgPackLoader::load)
    .def("save", &CMsgPackLoader::save)
    .def_readwrite("creature_attr_def_info", &CMsgPackLoader::creature_attr_def_info);

}
